name: Build and Package Burp Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v3
      with:
        name: burp-plugin
        path: build/libs/*.jar
